# Generated by Django 4.2.3 on 2023-07-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=40)),
                ("content", models.CharField(max_length=300)),
                ("pub_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
